name       : audacious
version    : 3.7.1
release    : 4
source     :
    - http://distfiles.audacious-media-player.org/audacious-3.7.1-gtk3.tar.bz2 : 30d63066916d0de32891c74b6b39e3c9e81fc2449274eba3d0a9b8c9f70d02eb
license    : GPL-3.0 
summary    : Audacious is an open source audio player.
description: |
    Audacious is an open source audio player. A descendant of XMMS, Audacious plays your music how you want it, without stealing away your computer’s resources from other tasks.
clang      : no
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libguess)
setup      : |
    %configure --prefix=/usr
build      : |
    %make
install    : |
    %make_install
