name       : audacious
version    : 3.6.2
release    : 2
source     :
    - http://distfiles.audacious-media-player.org/audacious-3.6.2-gtk3.tar.bz2 : ed951e588a9f3cb6766301cc387138a3fe2abc81c243eba478e4261390cb51ed
license    : GPL-3.0 
summary    : Audacious is an open source audio player.
description: |
    Audacious is an open source audio player. A descendant of XMMS, Audacious plays your music how you want it, without stealing away your computer’s resources from other tasks.
clang      : no
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libguess)
setup      : |
    %configure --prefix=/usr
build      : |
    %make
install    : |
    %make_install
