name       : audacious
version    : 3.7
release    : 3
source     :
    - http://distfiles.audacious-media-player.org/audacious-3.7-gtk3.tar.bz2 : cb2bdec9ab5ed4355d0ee105279f71595b36531345dd7161f4955c0e9812f40b
license    : GPL-3.0 
summary    : Audacious is an open source audio player.
description: |
    Audacious is an open source audio player. A descendant of XMMS, Audacious plays your music how you want it, without stealing away your computer’s resources from other tasks.
clang      : no
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libguess)
setup      : |
    %configure --prefix=/usr
build      : |
    %make
install    : |
    %make_install
