name       : audacious
version    : 3.7.2
release    : 5
source     :
    - http://distfiles.audacious-media-player.org/audacious-3.7.2-gtk3.tar.bz2 : bf9ce9e2f475d14cf6510e14235e858a73afb67826b039c2b6e0f86851ec7edf
license    : GPL-3.0 
component  : desktop.multimedia
summary    : Audacious is an open source audio player.
description: |
    Audacious is an open source audio player. A descendant of XMMS, Audacious plays your music how you want it, without stealing away your computer’s resources from other tasks.
clang      : no
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libguess)
rundeps    :
    - audacious-plugins
setup      : |
    %configure --prefix=/usr
build      : |
    %make
install    : |
    %make_install
