name       : audacious
version    : '4.1'
release    : 34
source     :
    - https://distfiles.audacious-media-player.org/audacious-4.1.tar.bz2 : 1f58858f9789e867c513b5272987f13bdfb09332b03c2814ad4c6e29f525e35c
license    : GPL-3.0-or-later
component  :
    - multimedia.audio
    - libs : multimedia.library
    - libs-devel : programming.devel
summary    : Audacious is an open source audio player
description: |
    Audacious is an open source audio player. A descendant of XMMS, Audacious plays your music how you want it, without stealing away your computer’s resources from other tasks.
optimize   : lto
builddeps  :
    - pkgconfig(Qt5UiTools)
rundeps    :
    - audacious-plugins
    - libs-devel :
        - audacious-libs
patterns   :
    - libs-devel :
        - /usr/include
        - /usr/lib64/lib*.so
        - /usr/lib64/pkgconfig
    - libs :
        - /usr/lib64/lib*.so.*
replaces   :
    - libs-devel : audacious-devel
setup      : |
    %meson_configure -Dbuildstamp="Solus package" -Dgtk=false
build      : |
    %ninja_build
install    : |
    %ninja_install
