name       : audacious
version    : '3.9'
release    : 17
source     :
    - https://github.com/audacious-media-player/audacious/archive/audacious-3.9-gtk3.tar.gz : a9e4cfdf9e7bd46891445164622f5702802e352ae7b8fc7f8ea5d16a051515d4
license    : GPL-3.0
component  :
    - multimedia.audio
    - libs : multimedia.library
    - libs-devel : programming.devel
summary    : Audacious is an open source audio player.
description: |
    Audacious is an open source audio player. A descendant of XMMS, Audacious plays your music how you want it, without stealing away your computer’s resources from other tasks.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libguess)
rundeps    :
    - audacious-plugins
patterns   :
    - libs-devel :
        - /usr/include
        - /usr/lib64/lib*.so
        - /usr/lib64/pkgconfig
    - libs :
        - /usr/lib64/lib*.so.*
replaces   :
    - libs-devel : audacious-devel
setup      : |
    sed -i 's inode/directory;  ' audacious.desktop
    %autogen --prefix=/usr \
             --with-buildstamp="Solus package"
build      : |
    %make
install    : |
    %make_install
