name       : audacious
version    : '4.3'
release    : 36
source     :
    - https://distfiles.audacious-media-player.org/audacious-4.3.tar.bz2 : 27584dc845c7e70db8c9267990945f17322a1ecc80ff8b452e9ca916a0ce9091
license    : GPL-3.0-or-later
component  :
    - multimedia.audio
    - libs : multimedia.library
    - libs-devel : programming.devel
summary    : Audacious is an open source audio player
description: |
    Audacious is an open source audio player. A descendant of XMMS, Audacious plays your music how you want it, without stealing away your computer’s resources from other tasks.
optimize   : lto
builddeps  :
    - pkgconfig(Qt5UiTools)
    - pkgconfig(libarchive)
rundeps    :
    - audacious-plugins
    - libs-devel :
        - audacious-libs
patterns   :
    - libs-devel :
        - /usr/include
        - /usr/lib64/lib*.so
        - /usr/lib64/pkgconfig
    - libs :
        - /usr/lib64/lib*.so.*
replaces   :
    - libs-devel : audacious-devel
setup      : |
    %meson_configure \
        -Dbuildstamp="Solus package" \
        -Dgtk=false \
        -Dlibarchive=true
build      : |
    %ninja_build
install    : |
    %ninja_install
