name       : audacious
version    : '3.8'
release    : 13
source     :
    - http://distfiles.audacious-media-player.org/audacious-3.8-gtk3.tar.bz2 : 38a5ba0c6e9d739a4bb5696c4178a45f4e3cb025905fdfb96654947593fbed66
license    : GPL-3.0
component  :
    - desktop.multimedia
    - libs : multimedia.library
    - libs-devel : programming.devel
summary    : Audacious is an open source audio player.
description: |
    Audacious is an open source audio player. A descendant of XMMS, Audacious plays your music how you want it, without stealing away your computer’s resources from other tasks.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libguess)
rundeps    :
    - audacious-plugins
patterns   :
    - libs-devel :
        - /usr/include
        - /usr/lib64/lib*.so
        - /usr/lib64/pkgconfig
    - libs :
        - /usr/lib64/lib*.so.*
replaces   :
    - libs-devel : audacious-devel
setup      : |
    sed -i 's inode/directory;  ' audacious.desktop
    %configure --prefix=/usr
build      : |
    %make
install    : |
    %make_install
